### ***Hello world! I’m Valent***
![sanemi](img/ezgif.com-video-to-gif-converter.gif)

<!--
**vlntmd/vlntmd** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
***A student who loves exploring new technologies and frameworks. I’m always exploring new trends, from AI to blockchain, and constantly developing my skills.Coding isn’t just my job,it’s my passion. Feel free to connect with me on GitHub or through my social media!***
